import marimo

__generated_with = "0.23.16"
app = marimo.App(width="medium")


@app.cell
def _():
    return


@app.cell
def _():
    import marimo as mo
    import matplotlib.pyplot as plt
    import numpy as np
    import pandas as pd

    return mo, np, pd, plt


@app.cell
def _(pd):
    # Load the CSV generated by the C++ benchmark.
    file = pd.read_csv(
        "/home/pushkar/computational_materials_learning/"
        "data/l2_stability.csv"
    )

    file.head()
    return (file,)


@app.cell
def _(pd):
    file = pd.read_csv(
        "/home/pushkar/computational_materials_learning/"
        "data/l2_stability.csv"
    )

    numeric_columns = [
        "exponent",
        "naive",
        "stable",
        "reference",
    ]

    for column in numeric_columns:
        file[column] = pd.to_numeric(
            file[column],
            errors="coerce",
        )

    file.head()
    return (file,)


@app.cell
def _(file, np):
    # Extract benchmark quantities.
    exponent = file["exponent"].to_numpy()
    naive = file["naive"].to_numpy()
    stable = file["stable"].to_numpy()
    reference = file["reference"].to_numpy()

    # Relative errors with respect to the analytical solution.
    stable_relative_error = (
        np.abs(stable - reference) / np.abs(reference)
    )

    # Only calculate the naive relative error where the naive result
    # is finite. At the extremes it deliberately becomes 0 or inf.
    naive_relative_error = np.full_like(
        naive,
        np.nan,
        dtype=float,
    )

    valid_naive = (
        np.isfinite(naive)
        & (naive > 0.0)
        & np.isfinite(reference)
        & (reference > 0.0)
    )

    naive_relative_error[valid_naive] = (
        np.abs(
            naive[valid_naive]
            - reference[valid_naive]
        )
        / np.abs(reference[valid_naive])
    )
    return naive_relative_error, stable_relative_error


@app.cell
def _(file, np):
    print(file[["naive", "stable", "reference"]].describe())

    print(
        "Naive inf:",
        np.isinf(file["naive"]).sum(),
    )

    print(
        "Stable inf:",
        np.isinf(file["stable"]).sum(),
    )

    print(
        "Reference inf:",
        np.isinf(file["reference"]).sum(),
    )

    print(
        "Naive zero:",
        (file["naive"] == 0.0).sum(),
    )

    print(
        "Stable zero:",
        (file["stable"] == 0.0).sum(),
    )
    return


@app.cell
def _(file, np):
    # Find the actual failure regions produced by this machine/run.
    naive_zero_rows = file[file["naive"] == 0.0]

    naive_inf_rows = file[
        np.isinf(file["naive"])
    ]

    print("Naive underflow-to-zero rows:")
    print(
        naive_zero_rows[
            ["exponent", "naive", "stable", "reference"]
        ]
    )

    print("\nNaive overflow-to-inf rows:")
    print(
        naive_inf_rows[
            ["exponent", "naive", "stable", "reference"]
        ]
    )
    return


@app.cell
def _(file, np):
    # Work in log10 space rather than asking Matplotlib's logarithmic
    # scale machinery to span approximately 600 orders of magnitude.
    log10_reference = np.log10(
        file["reference"].to_numpy()
    )

    log10_stable = np.log10(
        file["stable"].to_numpy()
    )

    log10_naive = np.full(
        len(file),
        np.nan,
        dtype=float,
    )

    valid_naive = (
        np.isfinite(file["naive"].to_numpy())
        & (file["naive"].to_numpy() > 0.0)
    )

    log10_naive[valid_naive] = np.log10(
        file.loc[valid_naive, "naive"].to_numpy()
    )
    return log10_naive, log10_reference, log10_stable


@app.cell
def _(file, log10_naive, log10_reference, log10_stable, plt):
    fig, ax = plt.subplots()

    ax.plot(
        file["exponent"],
        log10_reference,
        label="Analytical reference",
    )

    ax.plot(
        file["exponent"],
        log10_naive,
        label="Naive L2",
    )

    ax.plot(
        file["exponent"],
        log10_stable,
        label="Stable L2",
    )

    ax.set_xlabel("Exponent p")
    ax.set_ylabel("log10(L2 norm)")
    ax.set_title(
        "L2 norm stability across floating-point magnitudes"
    )

    ax.legend()

    fig
    return


@app.cell
def _(mo):
    mo.md(r"""
    ## Interpretation

    For an error vector

    \[
    e = [10^p,10^p],
    \]

    the exact norm is

    \[
    \|e\|_2 = \sqrt{2}\,10^p.
    \]

    The naïve implementation evaluates

    \[
    \sqrt{e_1^2+e_2^2}.
    \]

    At sufficiently negative exponents, the intermediate squared
    values approach the underflow region of double precision.
    Consequently, the naïve result can collapse to zero even while
    the mathematical norm is nonzero.

    At sufficiently positive exponents, the intermediate squared
    values overflow to infinity even though the final mathematical
    norm may still be representable.

    The stable scaled-sum-of-squares implementation avoids directly
    forming these extreme squares. Instead, it works primarily with
    ratios whose magnitudes satisfy

    \[
    0 \le r \le 1.
    \]

    Therefore, the representable range of the final mathematical
    answer is different from the representable range required by
    the intermediate arithmetic of a particular numerical
    algorithm.

    This demonstrates an important numerical-computing principle:
    two algebraically equivalent algorithms can have very different
    floating-point stability.
    """)
    return


@app.cell
def _(naive_relative_error, np, stable_relative_error):
    finite_naive_error = naive_relative_error[
        np.isfinite(naive_relative_error)
    ]

    finite_stable_error = stable_relative_error[
        np.isfinite(stable_relative_error)
    ]

    if finite_naive_error.size > 0:
        print(
            "Maximum finite naive relative error:",
            np.max(finite_naive_error),
        )

    if finite_stable_error.size > 0:
        print(
            "Maximum finite stable relative error:",
            np.max(finite_stable_error),
        )
    return


if __name__ == "__main__":
    app.run()
