"""
Analyze the conditioning of a nearly singular 2x2 linear system.

This module examines the matrix family

    A(epsilon) = [[1, 1],
                  [1, 1 + epsilon]],

where epsilon > 0 controls the distance from singularity. The determinant is

    det(A) = epsilon,

so the matrix approaches singularity as epsilon approaches zero.

For this matrix, the infinity-norm condition number is

    kappa_inf(A) = (2 + epsilon)^2 / epsilon.

Therefore, in the limit epsilon -> 0,

    kappa_inf(A) ~ 4 / epsilon.

The analysis reads condition numbers generated by the C++ numerical core,
estimates their log-log scaling with epsilon, and compares the computed
results with the asymptotic 4/epsilon behavior.
"""
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

file = pd.read_csv(
    "/home/pushkar/computational_materials_learning/data/conditioning_results.csv",
    sep="\t",
)
epsilon = np.array(file["epsilon"])
condition_number = np.array(file["condition_number"])


def asymptotic_slope(epsilon, condition_number):
    """
    Estimate the log-log slope of condition number versus epsilon.
    """
    x = np.log(epsilon)
    y = np.log(condition_number)
    slope, intercept = np.polyfit(x, y, 1)
    print(f"slope={slope},intercept={intercept}")
    return slope  # Tip: Add a return statement so your test can verify the value!

fig, ax = plt.subplots()

ax.loglog(
    epsilon,
    condition_number,
    "o-",
    label=r"$\kappa_\infty(A)$"
)
#plt.plot(epsilon,condition_number,label='Measured')
plt.plot(epsilon,4.0/epsilon,label='Reference')
plt.xlabel("Epsilon")
plt.ylabel("Infinity_Norm_Condition_Number")
plt.legend()
plt.savefig("data/conditioning_scaling.png")
print(f"Measured Log-Log Slope = {asymptotic_slope(epsilon,condition_number)}")

